"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.TRANSFER_STATUS = void 0;
var TRANSFER_STATUS;
(function (TRANSFER_STATUS) {
    TRANSFER_STATUS["REQUESTED"] = "REQUESTED";
    TRANSFER_STATUS["ACCEPTED"] = "ACCEPTED";
    TRANSFER_STATUS["CHANGE_REQUESTED"] = "CHANGE_REQUESTED";
    TRANSFER_STATUS["TRANSFERRED"] = "TRANSFERRED";
})(TRANSFER_STATUS = exports.TRANSFER_STATUS || (exports.TRANSFER_STATUS = {}));
