export enum JSON_TYPE {
  VERIFIABLE_CREDENTIAL = 'VerifiableCredential',
  PLACE = 'Place',
  GEO_COORDINATES = 'GeoCoordinates',
  POSTAL_ADDRESS = 'PostalAddress',
  PARCEL_DELIVERY = 'ParcelDelivery',
  PRODUCT = 'Product',
  ORGANIZATION = 'Organization',
  ENTITY = 'Entity',
  OBSERVATION = 'Observation',
  MEASURED_VALUE = 'MeasuredValue',
  QUANTITATIVE_VALUE = 'QuantitativeValue',
  INBOND = 'Inbond',
  BILL_OF_LADING = 'BillOfLading',
  INSPECTION_REPORT = 'InspectionReport',
  REVOCATION_LIST_2020_STATUS = 'RevocationList2020Status',
  REVOCATION_LIST_2020_CREDENTIAL = 'RevocationList2020Credential',
  REVOCATION_LIST_2020 = 'RevocationList2020',
  CUSTOM_PRODUCT = 'ExtProduct',
  CUSTOM_ORGANIZATION = 'ExtOrganization',
  ED25519SIGNATURE2020 = 'Ed25519Signature2020',
  ED25519SIGNATURE2018 = 'Ed25519Signature2018',
  JsonWebSignature2020 = 'JsonWebSignature2020',
  COMMODITY = 'Commodity',
  StatusList2021Entry = 'StatusList2021Entry',
  ENTRY_NUMBER = 'EntryNumber'
}
