export enum JSON_TYPE {
  VERIFIABLE_CREDENTIAL = 'VerifiableCredential',
  PLACE = 'Place',
  GEO_COORDINATES = 'GeoCoordinates',
  POSTAL_ADDRESS = 'PostalAddress',
  PARCEL_DELIVERY = 'ParcelDelivery',
  PRODUCT = 'Product',
  ORGANIZATION = 'Organization',
  OBSERVATION = 'Observation',
  MEASURED_VALUE = 'MeasuredValue',
  QUANTITATIVE_VALUE = 'QuantitativeValue',
  INBOND = 'Inbond',
  BILL_OF_LADING = 'BillOfLading',
  INSPECTION_REPORT = 'InspectionReport',
  REVOCATION_LIST_2020_STATUS = 'RevocationList2020Status',
  REVOCATION_LIST_2020_CREDENTIAL = 'RevocationList2020Credential',
  REVOCATION_LIST_2020 = 'RevocationList2020',
  CUSTOM_PRODUCT = 'product-extend',
  CUSTOM_ORGANIZATION = 'organization-extend',
  ED25519SIGNATURE2020 = 'Ed25519Signature2020'
}
