name: CI/CD

on:
  push:
    branches: [master]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - run: npm ci
      - run: npm run lint

  bump-version:
    name: 'Bump Version on master'
    runs-on: ubuntu-latest
    needs: [lint]
    outputs:
      newTag: ${{ steps.bump-version.outputs.newTag }}
    steps:
      - uses: actions/checkout@v2
      - name: Automated Version Bump
        id: bump-version
        uses: phips28/gh-action-bump-version@v9.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit-message: 'CI: bumps version to {{version}}'

  pre-release:
    name: 'Pre Release'
    runs-on: 'ubuntu-latest'
    needs: [bump-version]

    steps:
      - uses: 'marvinpinto/action-automatic-releases@latest'
        with:
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          automatic_release_tag: 'latest'
          prerelease: true
          title: 'Development Build'

  publish-package:
    runs-on: ubuntu-latest
    needs: [bump-version]
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com'
          # Defaults to the user or organization that owns the workflow file
          scope: '@mavennet'
      - run: npm ci
      - run: echo $NEW_TAG
        env:
          NEW_TAG: ${{ needs.bump-version.outputs.newTag }}
      - run: npm version $NEW_TAG --no-git-tag-version
        env:
          NEW_TAG: ${{ needs.bump-version.outputs.newTag }}
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
