"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.JSON_TYPE = void 0;
var JSON_TYPE;
(function (JSON_TYPE) {
    JSON_TYPE["VERIFIABLE_CREDENTIAL"] = "VerifiableCredential";
    JSON_TYPE["PLACE"] = "Place";
    JSON_TYPE["GEO_COORDINATES"] = "GeoCoordinates";
    JSON_TYPE["POSTAL_ADDRESS"] = "PostalAddress";
    JSON_TYPE["PARCEL_DELIVERY"] = "ParcelDelivery";
    JSON_TYPE["PRODUCT"] = "Product";
    JSON_TYPE["ORGANIZATION"] = "Organization";
    JSON_TYPE["ENTITY"] = "Entity";
    JSON_TYPE["OBSERVATION"] = "Observation";
    JSON_TYPE["MEASURED_VALUE"] = "MeasuredValue";
    JSON_TYPE["QUANTITATIVE_VALUE"] = "QuantitativeValue";
    JSON_TYPE["INBOND"] = "Inbond";
    JSON_TYPE["BILL_OF_LADING"] = "BillOfLading";
    JSON_TYPE["INSPECTION_REPORT"] = "InspectionReport";
    JSON_TYPE["REVOCATION_LIST_2020_STATUS"] = "RevocationList2020Status";
    JSON_TYPE["REVOCATION_LIST_2020_CREDENTIAL"] = "RevocationList2020Credential";
    JSON_TYPE["REVOCATION_LIST_2020"] = "RevocationList2020";
    JSON_TYPE["CUSTOM_PRODUCT"] = "ExtProduct";
    JSON_TYPE["CUSTOM_ORGANIZATION"] = "ExtOrganization";
    JSON_TYPE["ED25519SIGNATURE2020"] = "Ed25519Signature2020";
    JSON_TYPE["ED25519SIGNATURE2018"] = "Ed25519Signature2018";
})(JSON_TYPE = exports.JSON_TYPE || (exports.JSON_TYPE = {}));
