export var PROOF_PURPOSE_TYPE;
(function (PROOF_PURPOSE_TYPE) {
    PROOF_PURPOSE_TYPE["ASSERTION_METHOD"] = "assertionMethod";
    PROOF_PURPOSE_TYPE["AUTHENTICATION"] = "authentication";
})(PROOF_PURPOSE_TYPE || (PROOF_PURPOSE_TYPE = {}));
